version: '3.6'
services:

    # UI
    ui:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                BUILD_TARGET: 'dev'
        container_name: abnfix-ui
        ports:
            - '80:5173'
        restart: unless-stopped
        volumes:
            - ./:/usr/src
            - ./.env:/usr/src/.env
            - ./node_modules:/usr/src/node_modules
